### ISSUE TITLE
Crear claves para utilizar en indexador: Modelo 190 para casillas de mayor uso

### ISSUE THREAD

**Issue by mdiago** [mdiago/AeatModelos#2]
**Modelo 190**

Crear claves para las casillas cuyo texto descriptivo es:

* 'PERCEPCIONES DINERARIAS NO DERIVADAS DE INCAPACIDAD LABORAL. PERCEPCIÓN ÍNTEGRA'

* 'PERCEPCIONES DINERARIAS NO DERIVADAS DE INCAPACIDAD LABORAL. RETENCIONES PRACTICADAS'

Podrías ser las claves 'NoIncapacidadPercepcion' y 'NoIncapacidadRetencion'.  Es necesario crear claves similares para el resto de casillas de uso común también.

**Comment by bautista225** [comment]
Cierre por implementación realizada en su momento.
